name: Discord Notification

on:
  pull_request:
    types: [opened, closed, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
      - name: Send Message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#9B7DD4"
          message: "A new pull request on {{ EVENT_PAYLOAD.repository.full_name }} has created."
