name: Discord Notification

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '{
            "embeds": [{
              "title":"Notification",
              "description": "A new pull request has been created.",
              "color": "#9B7DD4"
              }]
            }'
        uses: Ilshidur/action-discord@master
        with:
          args: "The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed."
