name: Go Code Linter

on: [push, pull_request, issues, fork, watch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
      - name: Go-linter
        uses: Jerome1337/golint-action@v1.0.3
